name: Weekly update

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
  - cron: "0 7 * * 0"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  run-weekly-update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
    # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - run: pip install -r requirements.txt
    - run: python updateweekly.py

    - name: Commit and push changed files
      uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: Automated weekly update
        file_pattern: 'data/fights.json data/ratings-history.json data/ratings.csv'
